export const ALLOWED_FILE_TYPES = {
  HERO_SLIDES: ['jpg', 'jpeg', 'png'],
  DOCUMENTS: [
    'pdf',
    'odt',
    'ods',
    'odp',
    'docx',
    'xlsx',
    'pptx',
    'jpg',
    'jpeg',
    'png',
    'webp',
    'mp4',
    'webm',
    'mp3',
    'ogg',
  ],
  QUICK_ACCESS: ['jpg', 'jpeg', 'png'],
  COMMUNICATIONS: ['pdf'],
};
