export * from "./portal-communications.controller"
export * from "./portal-tutorials.controller"
export * from "./portal-documents.controller"
export * from "./portal-directory.controller"
export * from "./portal-calendar.controller"
export * from "./portal.controller"